db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/auctionsystem?sslMode=VERIFY_IDENTITY&useUnicode=true&characterEncoding=UTF-8
db.user=qoTiRchwRFMBBCc.root
db.password=hAFP1A9vHwG2Ox9f