db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://sq7-49.h.filess.io:3307/AuctionSystem_wholezoono?useSSL=false&allowPublicKeyRetrieval=true
db.user=AuctionSystem_wholezoono
db.password=d550066c503924fe2ae0c3d6d2ee044d3b49c09d