db.driver=com.mysql.cj.jdbc.Driver
db.url=jdbc:mysql://gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/auctionsystem?sslMode=VERIFY_IDENTITY&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Ho_Chi_Minh&forceConnectionTimeZoneToSession=true
db.user=Mtvqn54fxNSEedW.root
db.password=J8iqJ41SrrN1GB8X