name: CI/CD for Auction System

on:
  push:
    branches: [ main, dev , Refactor]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'
          cache: maven

      - name: Run tests
        run: mvn verify


      # Build Fat JAR (shade plugin bundle cả 3 platform natives)
      - name: Package Fat JARs
        run: mvn package -DskipTests

      - name: Upload client Fat JAR
        uses: actions/upload-artifact@v4
        with:
          name: auction-client
          # Lấy file không có "-original" suffix (file shade tạo ra)
          path: client/target/auction-client.jar
          if-no-files-found: error

      - name: Upload server JAR
        uses: actions/upload-artifact@v4
        with:
          name: auction-server
          path: server/target/auction-server.jar
          if-no-files-found: error

