package server.common.enums;

public enum NotificationType {
  BID_PLACED,
  OUTBID,
  AUCTION_WON,
  AUCTION_LOST,
  AUCTION_STARTED,
  AUCTION_ENDED,
  PAYMENT_RECEIVED,
  PAYMENT_DUE,
  TIME_EXTENDED,
  SYSTEM,
  ITEM_APPROVED,
  ITEM_REJECTED
}
